# Generated by Django 3.2 on 2021-08-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_art',
        ),
        migrations.AddField(
            model_name='album',
            name='album_art_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='listening_to',
            field=models.BooleanField(),
        ),
    ]
