# Generated by Django 3.2 on 2021-08-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0003_auto_20210808_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
