# Generated by Django 3.2 on 2021-08-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0004_collection_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='backlogged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
