# Generated by Django 3.2 on 2021-08-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0005_auto_20210810_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['creator', 'title']},
        ),
    ]
