# Generated by Django 3.2 on 2021-08-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0007_auto_20210811_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
