# Generated by Django 3.1.5 on 2021-08-14 16:37

import album_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0012_auto_20210814_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='review',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='album',
            name='score',
            field=album_api.models.IntegerRangeField(blank=True, default=None),
        ),
    ]
