# Generated by Django 3.1.5 on 2021-08-14 16:39

import album_api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0014_auto_20210814_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='score',
            field=album_api.models.IntegerRangeField(blank=True, default=None, null=True),
        ),
    ]
