# Generated by Django 3.1.5 on 2021-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0015_auto_20210814_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='review',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
