# Generated by Django 3.1.5 on 2021-08-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0017_auto_20210814_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
