# Generated by Django 3.1.5 on 2021-08-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0018_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='manual_override',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
