# Generated by Django 3.1.5 on 2021-08-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0019_album_manual_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='manual_override',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
