# Generated by Django 3.2 on 2021-08-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0021_auto_20210814_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='current',
        ),
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
