# Generated by Django 3.2 on 2021-08-26 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album_api', '0024_album_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumListObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField(blank=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='album_api.album')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('album_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_objects', to='album_api.albumlistobject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
