# Generated by Django 3.2 on 2021-08-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0025_albumlistobject_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='album_object',
        ),
        migrations.AddField(
            model_name='albumlistobject',
            name='_list',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='album_objects', to='album_api.list'),
        ),
    ]
