# Generated by Django 3.2 on 2021-08-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0026_auto_20210826_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumlistobject',
            name='_list',
        ),
        migrations.AddField(
            model_name='list',
            name='album_object',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='album_objects', to='album_api.albumlistobject'),
            preserve_default=False,
        ),
    ]
