# Generated by Django 3.2 on 2021-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0028_auto_20210826_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
