# Generated by Django 3.2 on 2021-08-31 16:21

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('album_api', '0032_alter_album_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': [django.db.models.functions.text.Lower('creator'), django.db.models.functions.text.Lower('title')]},
        ),
    ]
